---
- name: Install machine learning libraries from conda main repos
  command: "{{ mc3path }}/bin/conda install {{ item }}"
  args:
      creates: "{{ home }}/miniconda3/lib/python3.7/site-packages/{{ item }}/__init__.py"
  with_items:
      - numpy
      - scipy
      - matplotlib
      - jupyter
      - ipykernel
      - spyder
      - pandas
      - plotly
      - scikit-learn
- name: Install machine learning libraries from conda-forge repos
  command: "{{ mc3path }}/bin/conda install -c conda-forge {{ item }}"
  args:
      creates: "{{ home }}/miniconda3/lib/python3.7/site-packages/{{ item }}/__init__.py"
  with_items:
      - folium
- name: Put Spyder shortcut on Desktop
  copy:
      src: "{{ item }}"
      dest: "{{ home }}/Desktop/{{ item }}"
      mode: 0775
  with_items:
      - Spyder.desktop
      - JupyterNotebook.desktop
- name: Ensure spyder config folder exists
  file:
      path: "{{ home }}/.config/spyder-py3/config"
      state: directory
      mode: 0755
- name: Set default color scheme to scintilla
  lineinfile:
      path: "{{ home }}/.config/spyder-py3/config/spyder.ini"
      regexp: '^selected ='
      line: 'selected = scintilla'
