---
- name: Change user & group for wiki folder
  file:
    path=/vagrant/w
    owner=ubuntu
    group=www-data
    recurse=yes
- name: Install RDFIO including dependencies via composer
  composer:
    command=require
    arguments="rdfio/rdfio {{ rdfiover }} --update-no-dev"
    working_dir={{ mw_dir }}
- name: Activate full OWL export, as needed by RDFIO
  lineinfile:
    line='$smwgOWLFullExport = true;'
    dest={{ mw_dir }}/LocalSettings.php
    state=present
- name: Set up ARC2 tables
  shell: cd {{ mw_dir }}/extensions/Rdfio/maintenance; php setupStore.php;
- name: Import some initial wiki content
  shell: >
    php {{ mw_dir }}/maintenance/importDump.php /vagrant/roles/rdfio/files/wiki_content.xml
